// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eattnoxdvsftpyaztuxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdHRub3hkdnNmdHB5YXp0dXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTcxMDQsImV4cCI6MjA2MDU3MzEwNH0.Pl58F9XkwQZOq5vd6mP9tWN2IC7zyNo8WFRy2cw9wlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);